title: Dove Holes Brass Band
description: A public brass band in the heart of Derbyshire
baseurl: ""
url: "http://localhost:4000"
theme: minima
plugins:
  - jekyll-feed
exclude:
 - _config.yml
 - .bundle/
 - .sass-cache/
 - .jekyll-cache/
 - gemfiles/
 - Gemfile
 - Gemfile.lock
 - node_modules/
 - vendor/
